server:
  port: 80
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka

ribbon:
  ReadTimeout:  5000
  ConnectTimeout: 5000
logging:
  level:
    #用什么级别，监控哪个服务
    com.wutian.springcloud.service.PaymentFeignService: debug